name: ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  pinput: ^3.0.1
  connectivity_plus: ^5.0.0
#  webview_flutter: ^4.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/